apiVersion: v1
metadata:
  name: ocp419
baseDomain: crucible.iisl.com

controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}

compute:
  - name: worker
    replicas: 0

networking:
  networkType: OVNKubernetes
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
  machineNetwork:
    - cidr: 192.168.102.0/24

platform:
  baremetal:
    apiVIPs:
      - 192.168.102.10
    ingressVIPs:
      - 192.168.102.11

# Replace with your actual pull secret from cloud.redhat.com
pullSecret: 'SECRET'

# Replace with your SSH public key
sshKey: 'PUB-KEY'
